// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxgFziFW_H7YQz1-4G3trJq_z5mvFecY',
    appId: '1:431201958729:web:9a5c0df6dda811fcd0b898',
    messagingSenderId: '431201958729',
    projectId: 'deepguard-ai-3fbea',
    authDomain: 'deepguard-ai-3fbea.firebaseapp.com',
    storageBucket: 'deepguard-ai-3fbea.firebasestorage.app',
    measurementId: 'G-16RSSSZ1BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKEoEQtkhwufMN6y8UhEDYFGw_AgRSGM',
    appId: '1:431201958729:android:27f1a858fec04974d0b898',
    messagingSenderId: '431201958729',
    projectId: 'deepguard-ai-3fbea',
    storageBucket: 'deepguard-ai-3fbea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCIWYNqARBNpTb3R89HdsgXZHGnrsAFM',
    appId: '1:431201958729:ios:40df565896542484d0b898',
    messagingSenderId: '431201958729',
    projectId: 'deepguard-ai-3fbea',
    storageBucket: 'deepguard-ai-3fbea.firebasestorage.app',
    iosClientId: '431201958729-k5nocrgvijtjf8actrdqesabd7p11g70.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCIWYNqARBNpTb3R89HdsgXZHGnrsAFM',
    appId: '1:431201958729:ios:40df565896542484d0b898',
    messagingSenderId: '431201958729',
    projectId: 'deepguard-ai-3fbea',
    storageBucket: 'deepguard-ai-3fbea.firebasestorage.app',
    iosClientId: '431201958729-k5nocrgvijtjf8actrdqesabd7p11g70.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsxgFziFW_H7YQz1-4G3trJq_z5mvFecY',
    appId: '1:431201958729:web:a45942807ec9b2a9d0b898',
    messagingSenderId: '431201958729',
    projectId: 'deepguard-ai-3fbea',
    authDomain: 'deepguard-ai-3fbea.firebaseapp.com',
    storageBucket: 'deepguard-ai-3fbea.firebasestorage.app',
    measurementId: 'G-DZLZDQWBG5',
  );
}
